authoritative;
ddns-update-style interim;
allow booting;
allow bootp;
allow unknown-clients;
ignore client-updates;
default-lease-time 14400;
max-lease-time 14400;

subnet 172.16.16.0 netmask 255.255.255.0 {
 option routers                  172.16.16.198; # lan
 option subnet-mask              255.255.248.0;
 option domain-name              "ocp.lan";
 option domain-name-servers       172.16.16.198;
 range 172.16.18.170 172.16.18.189;
}

host ocp-bootstrap {
 hardware ethernet 00:0c:29:c2:97:dc;
 fixed-address 172.16.18.90;
}

host ocp-cp-1 {
 hardware ethernet 00:0c:29:a8:84:5a;
 fixed-address 172.16.18.91;
}

host ocp-cp-2 {
 hardware ethernet 00:0c:29:15:32:ce;
 fixed-address 172.16.18.92;
}

host ocp-cp-3 {
 hardware ethernet 00:0c:29:53:06:e3;
 fixed-address 172.16.18.93;
}

host ocp-w-1 {
 hardware ethernet 00:0c:29:38:36:a9;
 fixed-address 172.16.18.94;
}

host ocp-w-2 {
 hardware ethernet 00:0c:29:d7:df:aa;
 fixed-address 172.16.18.95;
}
